SELECT FLIGHT_NUMBER , LEG_NUMBER, AS.AVAILABLE_SEATS
FROM LEG_INSTANCE JOIN 
(
    SELECT MIN(FLIGHT_NUMBER) ,LEG_NUMBER , COUNT(*) as AVAILABLE_SEATS
    FROM SEAT_RESERVATION
    WHERE CUSTOMER_NAME != NULL
    GROUP BY FLIGHT_NUMBER , LEG_NUMBER
) as AS
ON LEG_INSTANCE.FLIGHT_NUMBER = SEAT_RESERVATION.FLIGHT_NUMBER AND LEG_INSTANCE.LEG_NUMBER = SEAT_RESERVATION.LEG_NUMBER
WHERE FLIGHT_NUMBER in 
(
    SELECT FLIGHT_NUMBER
    FROM LEG_INSTANCE
    WHERE COUNT(*) >= 2
    GROUP BY FLIGHT_NUMBER
)