SELECT FLIGHT_NUMBER , (FLIGHTS_FARES / NUMBER_OF_LEGS) as AVERAGE_FARES, DIFF_AIRPLANE
FROM (
    SELECT FLIGHT_NUMBER , COUNT(*) as NUMBER_OF_LEGS , COUNT (DISTINCT AIRPLANE_ID) as DIFF_AIRPLANE
    FROM FLIGHT_LEG
    GROUP BY FLIGHT_NUMBER
) as FL
    JOIN (
    SELECT FLIGHT_NUMBER , AMOUNT as FLIGHTS_FARES
    FROM FARES
) as FS
    ON FL.FLIGHT_NUMBER = FS.FLIGHT_NUMBER  